### ISSUE TITLE
IE 9 Layers added by Add Data dont display on the map when selected

### ISSUE THREAD

**Issue by Layoric** [NICTA/nationalmap#22] opened 2015-05-20 01:31 UTC
Hi Team,

Troy Gill here at GA came across an issue recently when testing the latest release on IE 9. Both Firefox and Chrome work as expected when added an external layer, but can't get data to show up on the map for IE9.

For the test, the following URL was used:

http://www.ga.gov.au/gis/services/topography/Dynamic_National_Map_Culture_and_Infrastructure/MapServer/WMSServer?request=GetCapabilities

No errors are shown and UI behaves the same as other browsers, just missing the data. After using the IE 9 network capture tool, it looks like the requests for layer image data just aren't being made by the application.

![image](https://cloud.githubusercontent.com/assets/234642/7717317/c112ce4a-fee2-11e4-8efc-a327aaf8a338.png)

Steps to reproduce:
1. Click Add Data
2. Paste provided URL and click add.
3. Select one/many layers from the added endpoint to view data.

Expected:
To see associated data on map (works in Chrome/Firefox)
Actual:
Map doesn't change in IE9

**Comment by kring** [comment] 2015-05-20 05:58
Thanks for the report @Layoric.  This is actually a problem with 2D in any browser, not just IE9.  The problem is that the server reports in its GetCapabilities that it only supports these CRSs:

```
<CRS>CRS:84</CRS>
<CRS>EPSG:4326</CRS>
<CRS>EPSG:4283</CRS>
```

This is almost certainly false.  This is an ArcGIS Server, so I'm sure it knows how to serve tiles in other projections.  But in any case, National Map believes the server and uses one of these projections.

The problem is, Leaflet _only_ supports the Web Mercator projection (EPSG:3857).  So in Leaflet, the map doesn't show up.  Of course, we should be showing a message to the user, at least, and I'll work on that.

One solution is to avoid using the WMS interface on an ArcGIS server.  Instead, have National Map talk to the native Esri MapServer REST interface.  This is already supported via an init file or start URL (but not via Add Data).  Here's a [giant URL](http://nationalmap.nicta.com.au/#start=%7B%22version%22%3A%220.0.04%22%2C%22initSources%22%3A%5B%22init%2Fnm.json%22%2C%7B%22catalog%22%3A%5B%7B%22type%22%3A%22group%22%2C%22name%22%3A%22User-Added%20Data%22%2C%22description%22%3A%22%22%2C%22info%22%3A%5B%5D%2C%22isUserSupplied%22%3Atrue%2C%22isOpen%22%3Atrue%2C%22items%22%3A%5B%7B%22type%22%3A%22esri-mapServer-group%22%2C%22name%22%3A%22Dynamic%20National%20Map%20Culture%20and%20Infrastructure%22%2C%22description%22%3A%22%22%2C%22info%22%3A%5B%5D%2C%22isUserSupplied%22%3Atrue%2C%22isOpen%22%3Atrue%2C%22items%22%3A%5B%5D%2C%22preserveOrder%22%3Afalse%2C%22url%22%3A%22http%3A%2F%2Fwww.ga.gov.au%2Fgis%2Frest%2Fservices%2Ftopography%2FDynamic_National_Map_Culture_and_Infrastructure%2FMapServer%22%7D%5D%2C%22preserveOrder%22%3Afalse%7D%5D%2C%22catalogIsUserSupplied%22%3Atrue%7D%2C%7B%22initialCamera%22%3A%7B%22west%22%3A100.82543115445205%2C%22south%22%3A-50.269977854142276%2C%22east%22%3A168.1822124031323%2C%22north%22%3A1.015842054479712%2C%22position%22%3A%7B%22x%22%3A-7663173.984778213%2C%22y%22%3A7797062.103355697%2C%22z%22%3A-5574354.586187877%7D%2C%22direction%22%3A%7B%22x%22%3A0.6244648002125202%2C%22y%22%3A-0.6353752163644171%2C%22z%22%3A0.4542488830205393%7D%2C%22up%22%3A%7B%22x%22%3A-0.31840886092851123%2C%22y%22%3A0.323971981824996%2C%22z%22%3A0.8908748241333303%7D%7D%2C%22homeCamera%22%3A%7B%22west%22%3A105.00000000000001%2C%22south%22%3A-45%2C%22east%22%3A155%2C%22north%22%3A-5%7D%2C%22baseMapName%22%3A%22Bing%20Maps%20Aerial%20with%20Labels%22%2C%22viewerMode%22%3A%223d%22%7D%5D%7D) that shows the dataset working.

I've actually already added the ability to add Esri MapServers via the Add Data panel, too, so that will be included in the next release (15 June at the latest).

**Comment by kring** [comment] 2015-05-21 00:17
I'm closing this now that I've opened a TerriaJS pull request (TerriaJS/terriajs#703) to address the lack of a message in this scenario.  Let me know if you have any concerns.

**Closed by kring** 2015-05-21 00:17 UTC

**Comment by Layoric** [comment] 2015-05-21 00:56
@kring Thanks for the detailed explination! Makes sense to deal with issue in Terria with a sensible error to help users. Cheers!
