### ISSUE TITLE
High-Latitude WMS 'Bug'(?)

### ISSUE THREAD

**Issue by the-epeecurean** [NICTA/nationalmap#106] opened 2015-08-25 19:13 UTC
I have been working with some data in the National Map application. I encountered one odd error loading WMS data that leads me to wonder if it is a limitation of the design, or a bug. 

When I load some of my datasets from a WMS in the Cesium Sandcastle (ie. the ice concentration layer shown in the attached images) it loads completely:

![iceconcentration_sandcastle](https://cloud.githubusercontent.com/assets/12992194/9476564/54199cec-4b3b-11e5-9d9d-06671ff6bb80.png)

However, when I load the same WMS into your implementation, a wedge of data is missing, extending from the North Pole out over the Bering Sea. I suspect higher latitudes are not what your application was aimed for, but I found this curious.

![iceconcentration_nicta](https://cloud.githubusercontent.com/assets/12992194/9476598/7e805d36-4b3b-11e5-9d4c-b75895e46659.png)

This same occurs no matter what dataset is loaded. I was wondering if you had any ideas as to why this might occur. I don’t believe it is in the settings of my geoserver data store, but want to be sure. I’d like something like this to work consistently. If it is a part of the design of National Map, perhaps you could point me where in the build this is effected? Thanks!

**Comment by meh9** [comment] 2015-08-26 00:36
I'm not sure which WMS service and specific layer you were using because I can't find an ice concentration layer in the Sandcastle, but using this service and specifying layer `ASARcoverageArctic201003` does show the same effect:

http://geos.polarview.aq/geoserver/polarview/wms

Looking at the requests, Sandcastle make requests for tiles using SRS EPSG:4326, while NationalMap requests EPSG:3857.

If you switch to 2D mode (matching the EPSG:3857 Mercator projection) in NationalMap you can also see that it looks like it's missing a straight strip of data with a little missing on either side of 180 degrees.

Maybe this is a server problem where if EPSG:3857 is requested it misses out data around the antimeridian?

**Comment by kring** [comment] 2015-11-16 23:28
Like @meh9 said, I think this is caused by the server missing data in the Web Mercator (EPSG:3857) projection.  I'm closing this for now, but @the-epeecurean please re-open it if you have further concerns or additional information.

**Closed by kring** 2015-11-16 23:28 UTC
